### ISSUE TITLE
Maven assembly doesn't pick up Millenaire language files

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftAdventureBoogaloo#3]
There are a few language files in Millenaire named 使用說明.txt and similar that don't get picked up by the maven assembly plugin. The pack will not start without them.

**Comment by UndeadZeratul** [comment]
Goddamnit Millenaire...

**Comment by Nincodedo** [comment]
Actually small update, they do get picked up but get named to something else. 使用說明 for example gets changed to ____.
